name: build & release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache flutter and pub packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: dependencies
        run: flutter pub get

      # --- Android build ---
      - name: Build APK (unsigned)
        run: flutter build apk --release --no-tree-shake-icons

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk tally.apk

      # --- iOS build ---
      - name: Build IPA (unsigned)
        run: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/tally.ipa Payload
          cd ../../..

      - name: Move IPA to root
        run: mv build/ios/ipa/tally.ipa tally.ipa

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Tally Latest Build
          files: |
            tally.apk
            tally.ipa
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
