name: build & release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # --- Cache dependencies ---
      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Set up Flutter (latest stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      # --- Android build ---
      - name: Build unsigned APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk tally.apk

      # --- iOS build ---
      - name: Build unsigned IPA
        run: |
          flutter build ios --release --no-codesign --no-tree-shake-icons
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/tally.ipa Payload
          cd ../../..

      - name: Move IPA to root
        run: mv build/ios/ipa/tally.ipa tally.ipa

      # --- Release upload ---
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "tally build #${{ github.run_number }}"
          body: ${{ github.event.head_commit.message }}
          files: |
            tally.apk
            tally.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
